services:
  - type: worker
    name: discord-bot
    runtime: python
    buildCommand: pip install --force-reinstall --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
